controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile2 = sprites.createProjectileFromSide(img`
        ................................
        ..............aaa...............
        .............aaaaa..............
        ............a.aaa.a.............
        ...........a..aaa..a............
        ..............aaa...............
        ..............aaa...............
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `, 0, 50)
})
let projectile2: Sprite = null
game.splash("Benvingut", "Apreta A per començar i B per disparar")
effects.starField.startScreenEffect()
let Nave = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . 2 . . . . . . . . 
    . . . . . . 2 2 2 . . . . . . . 
    . . . . . 2 2 2 2 2 . . . . . . 
    . . . . 2 2 2 2 2 2 2 . . . . . 
    . . . . . . 2 2 2 . . . . . . . 
    . . . 2 2 2 2 2 2 2 2 2 . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
Nave.setPosition(76, 110)
controller.moveSprite(Nave, 100, 100)
Nave.setStayInScreen(true)
info.setLife(3)
game.onUpdateInterval(1000, function () {
    projectile2 = sprites.createProjectileFromSide(img`
        ................................
        ................................
        ..........bbbbbbbbbbbb..........
        .......bbb331111333333bbb.......
        .....cbb3331111113333333bbb.....
        ....cb33333311113333333111db....
        ...cb3111133333333333311111db...
        ..cbb1111113333333333311111ddc..
        .cbbd1111113333333333331111ddbc.
        cbbbdd11111333333111333311ddbbbc
        cbbbdddd1133333311111333bbbbbbbc
        ccbbbddddbbb33331111dbbbbbbbbbcc
        .ccbbbbbbbbbbbbbbdddbbbbbbbbbcc.
        ..cccbbbbbbbbbbbbbbbbbbbbbbccc..
        .....cccccccccccccccccccccc.....
        ..........bbbdddd11dbb..........
        `, 0, 50)
    Nave.x += randint(0, scene.screenWidth())
    Nave.setKind(SpriteKind.Player)
})
